version: '2.4'
services:
  db:
    image: mysql
    container_name: java_core_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
     - 3306:3306
    volumes:
      - java_core_data:/var/lib/mysql

volumes:
  java_core_data: